controller_manager:
  ros__parameters:
    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"

    joint_trajectory_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"

joint_trajectory_controller:
  ros__parameters:
    joints:
      - RF_HAA
      - RF_HFE
      - RF_KFE
      - LF_HAA
      - LF_HFE
      - LF_KFE
      - RH_HAA
      - RH_HFE
      - RH_KFE
      - LH_HAA
      - LH_HFE
      - LH_KFE

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity

    gains:
      RF_HAA:
        p: 200.0
        i: 0.1
        d: 50.0
      RF_HFE:
        p: 150.0
        i: 0.1
        d: 25.0
      RF_KFE:
        p: 100.0
        i: 0.1
        d: 10.0
      LF_HAA:
        p: 200.0
        i: 0.1
        d: 50.0
      LF_HFE:
        p: 150.0
        i: 0.1
        d: 25.0
      LF_KFE:
        p: 100.0
        i: 0.1
        d: 10.0
      RH_HAA:
        p: 200.0
        i: 0.1
        d: 50.0
      RH_HFE:
        p: 150.0
        i: 0.1
        d: 25.0
      RH_KFE:
        p: 100.0
        i: 0.1
        d: 10.0
      LH_HAA:
        p: 200.0
        i: 0.1
        d: 50.0
      LH_HFE:
        p: 150.0
        i: 0.1
        d: 25.0
      LH_KFE:
        p: 100.0
        i: 0.1
        d: 10.0
